# Default constants
WIDTH = HEIGHT = 800
MIN_RADIUS = 75
MAX_RADIUS = 130
RADIUS_GROWTH = 0.8
CONTENTS_SHIFT_Y = 0.1
TITLE_SCALE_FACTOR = 9
CONTENTS_SCALE_FACTOR = 3
MIN_TITLE_TEXT_SIZE = 12
DEFAULT_TITLE_TEXT_SIZE = MIN_TITLE_TEXT_SIZE + MIN_RADIUS/TITLE_SCALE_FACTOR
MIN_TEXT_SIZE = 0
DEFAULT_CONTENTS_TEXT_SIZE = MIN_TEXT_SIZE + MIN_RADIUS/CONTENTS_SCALE_FACTOR
VELOCITY_MAX = 50

class Color:

    def __init__(self, r, g, b):
        self.r, self.g, self.b = r, g, b
